- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME')  }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME')  }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - import_tasks: tasks/core-setup.yaml
    - import_tasks: tasks/terminal.yaml
    - import_tasks: tasks/zsh.yaml
    - import_tasks: tasks/dotfiles.yaml
    - import_tasks: tasks/git-setup.yaml
    - import_tasks: tasks/lsp.yaml
    - import_tasks: tasks/node.yaml
    - import_tasks: tasks/npm.yaml
    - import_tasks: tasks/debugger.yaml
    - import_tasks: tasks/nvim.yaml
    - import_tasks: tasks/ssh.yaml

