- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: log the personal directory
      shell: "echo {{ personal }}"
    - name: log the user
      shell: "echo {{ user }}"
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
