- name: Debugger JavaScript Exists?
  stat:
    path: "{{ personal }}/microsoft-sucks/vscode-node-debug2"
  register: node_debugger
  tags:
    - install
    - debugger

- name: Debugger - JavaScript
  shell: 'git clone https://github.com/microsoft/vscode-node-debug2 {{ personal }}/microsoft-sucks/vscode-node-debug2'
  tags:
    - install
    - debugger
  when: node_debugger.stat.exists == False

- name: Debugger npm i and build JavaScript
  shell: cd {{ personal }}/microsoft-sucks/vscode-node-debug2 && npm i && npm run build
  tags:
    - install
    - debugger
