- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  shell: "git clone https://github.com/javierMorales9/.dotfiles {{ home }}/.dotfiles"
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: "cd {{ home }}/.dotfiles && ./ubuntu"
  tags:
    - install
    - dotfiles
    - stow
